-- MySQL Script generated by MySQL Workbench
-- Sat Jan 25 20:56:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`departments` (
  `idDepartments` INT NOT NULL AUTO_INCREMENT,
  `nameOtdel` VARCHAR(50) NOT NULL,
  `bossOtdel` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDepartments`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`teachers` (
  `idTeachers` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `otchestvo` VARCHAR(255) NOT NULL,
  `post` VARCHAR(255) NOT NULL,
  `phone` INT NOT NULL,
  `departments_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTeachers`),
  INDEX `departments_id` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `teachers_ibfk_1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `test`.`departments` (`idDepartments`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`lessons` (
  `idLessons` INT NOT NULL AUTO_INCREMENT,
  `nameLessons` VARCHAR(50) NOT NULL,
  `audition` INT NULL DEFAULT NULL,
  `teacher_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idLessons`),
  INDEX `teacher_id` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `lessons_ibfk_1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `test`.`teachers` (`idTeachers`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`specializations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`specializations` (
  `idSpecial` INT NOT NULL AUTO_INCREMENT,
  `nameSpecial` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSpecial`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`students` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `adress` VARCHAR(255) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `region` INT NOT NULL,
  `number` INT NOT NULL,
  `special_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `special_id` (`special_id` ASC) VISIBLE,
  CONSTRAINT `students_ibfk_1`
    FOREIGN KEY (`special_id`)
    REFERENCES `test`.`specializations` (`idSpecial`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`tests` (
  `idTest` INT NOT NULL AUTO_INCREMENT,
  `nameTest` VARCHAR(255) NOT NULL,
  `proiden` VARCHAR(10) NOT NULL,
  `ball` VARCHAR(50) NOT NULL,
  `lesson_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTest`),
  INDEX `lesson_id` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `tests_ibfk_1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `test`.`lessons` (`idLessons`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`result` (
  `idResult` INT NOT NULL AUTO_INCREMENT,
  `ocenka` INT NULL DEFAULT NULL,
  `dolg` VARCHAR(10) NULL DEFAULT NULL,
  `student_id` INT NULL DEFAULT NULL,
  `tests_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idResult`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `tests_id` (`tests_id` ASC) VISIBLE,
  CONSTRAINT `result_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `test`.`students` (`idStudent`),
  CONSTRAINT `result_ibfk_2`
    FOREIGN KEY (`tests_id`)
    REFERENCES `test`.`tests` (`idTest`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
